# Generated by Django 5.0.14 on 2026-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('role', models.CharField(max_length=200, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Фото')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('cert_primary', models.TextField(blank=True, verbose_name='Основной сертификат')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('other_certs', models.TextField(blank=True, help_text='Каждый сертификат с новой строки', verbose_name='Другие сертификаты')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'ordering': ['order', 'name'],
            },
        ),
    ]
