# Generated by Django 5.0.14 on 2026-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/files/', verbose_name='Файл для скачивания (PDF)')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Документ / Сертификат',
                'verbose_name_plural': 'Документы и сертификаты',
                'ordering': ['order', 'title'],
            },
        ),
    ]
