# Generated by Django 5.0.14 on 2026-06-19 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cert_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='UUID из localStorage браузера посетителя', unique=True, verbose_name='Ключ устройства')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало переписки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее сообщение')),
            ],
            options={
                'verbose_name': 'AI-чат — сессия',
                'verbose_name_plural': 'AI-чат — сессии',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'AI')], max_length=16, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.aichatsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'AI-чат — сообщение',
                'verbose_name_plural': 'AI-чат — сообщения',
                'ordering': ['created_at'],
            },
        ),
    ]
