# Generated by Django 5.0.14 on 2026-06-17 13:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Slug')),
                ('slug_ru', models.SlugField(blank=True, max_length=300, null=True, verbose_name='Slug')),
                ('slug_uz', models.SlugField(blank=True, max_length=300, null=True, verbose_name='Slug')),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Содержание (рус)')),
                ('body_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Mazmun (uzb)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/covers/', verbose_name='Обложка')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-created_at'],
            },
        ),
    ]
